# Generated by Django 5.0.6 on 2024-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1500)),
                ('author', models.CharField(max_length=1500)),
                ('genre', models.CharField(max_length=1500)),
                ('image', models.ImageField(upload_to='photos')),
                ('song', models.FileField(upload_to='photos')),
            ],
        ),
    ]
